sudo: required
services:
- docker

jobs:
  include:
    - stage: Build images
      name: 2019.11.21-buster
      script: docker build 2019.11.21/buster
    - name: 2019.11.21-slim-buster
      script: docker build 2019.11.21/buster/slim
    - name: 2019.11.21-alpine3.10
      script: docker build 2019.11.21/alpine3.10
